frontend:
  image: chengzh/frontend
  tag: latest
  autoscaling:
    averageUtilization: 90
backend:
  image: chengzh/backend
  tag: latest
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  
